[REFACTOR] Refactoring for Custom Response, Error
Kernel360/F2-ENGLISH-CHALLENGING-BE pull request #68
Opened 2024-10-01 13:26 UTC by tigris24

### PR 타입 (하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 문서 수정
- [ ] 리팩토링
- [ ] 스타일 수정
- [ ] 테스트 코드 추가
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
`refactor/#51/content-cralwer` -> `dev`

### 변경 사항
- Custom Response, Error 제작 및 적용

### 참고 사항
- 관련 이슈 번호: #51 

### 셀프 체크리스트
- [ ] 코드가 정상적으로 동작하는지 확인
- [ ] 새로운 테스트를 추가했거나 기존 테스트를 통과하는지 확인
- [ ] 코드 스타일 가이드에 맞게 포맷팅했는지 확인
- [ ] 관련 문서를 업데이트했는지 확인

2024-10-01 17:06 UTC, mooncw commented on src/main/java/com/echall/platform/config/SecurityConfig.java
> +		corsConfiguration.setAllowedOriginPatterns(Collections.singletonList("http://http://13.238.253.88:8080"));
http://가 2개에요!
그리고 웹서버와 인프라가 만들어지기 전에 일단 localhost:8080으로 하시는 게 어떠신가요?

2024-10-01 17:12 UTC, mooncw commented on src/main/java/com/echall/platform/config/WebConfig.java
> +}
ALLOWED_METHOD_NAMES.split(",")를 하면서까지 넣는 이유가 뭔가요?
저는 allowedMethods에 직접 메서드를 넣는게 좋아보입니다.

2024-10-01 17:14 UTC, mooncw commented on src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
> +		//
아무런 주석이 없다면 지워주세요!

2024-10-01 17:20 UTC, mooncw commented on src/main/java/com/echall/platform/message/ResponseCode.java
>  	INVALID_INPUT_VALUE("C-001", "Invalid Input Value", HttpStatus.BAD_REQUEST),
이 파일은 아직 필요해서 냅두신건가요?

2024-10-01 17:23 UTC, mooncw commented on src/main/java/com/echall/platform/message/response/UserResponseCode.java
> +	USER_GET_CHALLENGE(HttpStatus.OK, UserServiceStatus.USER_GET_INFO, "유저 챌린지 조회");
저희 ErrorCode와 SuccessCode 둘다 HttpStatus 컨벤션에 대해 이야기해봐요.

2024-10-01 17:24 UTC, mooncw commented on src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java
> +	BOOKMARK_UPDATE_SUCCESS("B-002"),
한현님이 말씀하시기를...

[커스텀에러코드컨벤션]
백엔드에서 커스텀 에러 코드를 작성하실 때, 프론트에서 쉽게 이해하고 디버깅하기 쉬운 형식을 고민해봤습니다.

문자열 기반 형식
예: USER_NOT_FOUND, PRODUCT_OUT_OF_STOCK, INVALID_PAYMENT_METHOD

숫자 + 문자열 조합
HTTP 상태 코드와 문자열로 메세지를 더 구체적으로 표현
예: 404_USER_NOT_FOUND, 400_INVALID_INPUT, 500_DATABASE_CONNECTION_ERROR

찬욱님이 이전 프로젝트에서 사용하신 4자리 숫자 방식은 프론트쪽에서 한 눈에 이해하기 어렵고 매번 문서를 찾아봐야하는 번거로움이 있을 것 같아서 위의 2 방식 중 편하신 걸로 해주시면 좋을 것 같습니다.

-디스코드 발췌.

2024-10-01 17:25 UTC, mooncw commented on src/main/java/com/echall/platform/oauth2/JwtProperties.java
> +
삐빅 의미없는 줄바꿈 발견.

2024-10-01 17:25 UTC, mooncw commented on src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
> +				() -> new RuntimeException(refreshToken)
여기는 왜 RuntimeException 인가요?

2024-10-01 17:33 UTC, mooncw commented on src/main/resources/yml/application-local.yml
> +    url: ${MY_LOCAL_DATA_SOURCE}
env 관리에 대해 이야기해보고 싶습니다!

2024-10-01 17:34 UTC, mooncw requested changes
코멘트 확인해주세요!

2024-10-02 02:23 UTC, tigris24 commented on src/main/java/com/echall/platform/config/WebConfig.java
> +}
이건 멘토님과 같이 코딩할 때 받았던 부분이라 그렇게 들어가 있었습니다
말씀하신대로 수정하겠습니다

2024-10-02 02:25 UTC, tigris24 commented on src/main/java/com/echall/platform/message/ResponseCode.java
>  	INVALID_INPUT_VALUE("C-001", "Invalid Input Value", HttpStatus.BAD_REQUEST),
넵 작업하면서 확인용으로 놔둔거고 머지할때는 삭제할 예정입니다

2024-10-02 02:25 UTC, tigris24 commented on src/main/java/com/echall/platform/oauth2/JwtProperties.java
> +
수정했습니다

2024-10-02 02:40 UTC, tigris24 commented on src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
> +				() -> new RuntimeException(refreshToken)
수정했습니다.

2024-10-02 02:44 UTC, tigris24 commented on src/main/java/com/echall/platform/config/SecurityConfig.java
> +		corsConfiguration.setAllowedOriginPatterns(Collections.singletonList("http://http://13.238.253.88:8080"));
네 일단 로컬만 남겨두었습니다

2024-10-02 02:44 UTC, tigris24 commented
[[REFACTOR] PR review 반영](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/68/commits/ea54054632b54448c2fc387249e059d09a2e8690)
의논할 부분 제외하고는 반영하였습니다.

2024-10-02 04:45 UTC, tigris24 commented on src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java
> +	BOOKMARK_UPDATE_SUCCESS("B-002"),
대면으로 의논하고 노션으로 정리 완료

2024-10-02 06:24 UTC, mooncw approved these changes
고생하셨습니다!

2024-10-02 06:24 UTC, merged